[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
domain = { path = "../domain" }
jiff = "0.2.19"
storage = { path = "../storage" }
tokio = { version = "1.49.0", features = ["full"] }
